name: ventasia_marketplace
description: SmartCartAI App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  image_picker: ^1.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_placeholder.png" # Place your purple logo here

flutter:
  uses-material-design: true
