export interface Product {
  id: number | string;
  name: string;
  category: string;
  price: number;
  originalPrice: number;
  discount: string | null;
  featured: boolean;
  image: string;
  vendorName: string;
  vendorRating: number;
  shippingTime: string;
  description: string;
  specs: string[];
}

export const products: Product[] = [
  {
    id: 1,
    name: "Silla de Oficina Ergonómica Premium",
    category: "Mobiliario",
    price: 199.99,
    originalPrice: 249.99,
    discount: "20%",
    featured: true,
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=800&q=80",
    vendorName: "ErgoOffice Tech",
    vendorRating: 4.8,
    shippingTime: "24-48 horas hábiles",
    description: "Nuestra silla ergonómica está diseñada con malla transpirable de alta tecnología. Cuenta con soporte lumbar ajustable en múltiples dimensiones, reposabrazos 3D y mecanismo sincrónico para la máxima comodidad durante exhaustivas jornadas de trabajo.",
    specs: ["Soporte lumbar ajustable", "Reposabrazos 3D", "Malla transpirable importada", "Ruedas silenciosas PU", "Capacidad: 150kg"]
  },
  {
    id: 2,
    name: "Monitor UltraWide 34\" 4K",
    category: "Tecnología",
    price: 499.99,
    originalPrice: 599.99,
    discount: "15%",
    featured: false,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
    vendorName: "DigitalDisplays Pro",
    vendorRating: 4.9,
    shippingTime: "3-5 días hábiles",
    description: "Maximiza tu productividad con este monitor curvo UltraWide 34\" con resolución 4K. Incluye paneles IPS con colores vibrantes sRGB 99% ideales para edición o tareas de desarrollo que requieren espacio. Su tasa de refresco ultra dinámica lo hace perfecto también para entretenimiento.",
    specs: ["Resolución: 3440 x 1440", "Panel IPS", "Color sRGB 99%", "Refresco: 144Hz", "Tiempo de respuesta: 1ms"]
  },
  {
    id: 3,
    name: "Teclado Mecánico Inalámbrico",
    category: "Accesorios",
    price: 89.99,
    originalPrice: 120.00,
    discount: "25%",
    featured: true,
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80",
    vendorName: "KeyTech Store",
    vendorRating: 4.6,
    shippingTime: "Dentro de 24 horas",
    description: "Elegante teclado mecánico inalámbrico ideal para minimalistas. Cuenta con switches silenciosos y una conexión estable por Bluetooth 5.0 o receptor 2.4Ghz. Su batería de gran capacidad garantiza hasta 2 meses de autonomía.",
    specs: ["Switches Brown (Táctiles, Silenciosos)", "Retroiluminación Blanca (Cálida)", "Triple modo de conexión", "Batería 4000mAh", "Teclas PBT"]
  },
  {
    id: 4,
    name: "Escritorio Elevable Automático",
    category: "Mobiliario",
    price: 349.99,
    originalPrice: 349.99,
    discount: null,
    featured: false,
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80",
    vendorName: "StandDesk Solutions",
    vendorRating: 4.7,
    shippingTime: "Envío pesado: 5-7 días",
    description: "Eleva tu bienestar en la oficina con nuestro escritorio elevable gracias a sus potentes motores dobles. Guarda hasta 4 perfiles de altura diferentes en su memoria integrada y despídete de los dolores de espalda por falta de movimiento regular.",
    specs: ["Motores duales silenciosos", "Alturas preestablecidas (4 botones de memoria)", "Capacidad de carga: 120kg", "Tablero de bambú ecológico", "Alarma de sedentarismo"]
  },
  {
    id: 5,
    name: "Auriculares Noise Cancelling Pro",
    category: "Tecnología",
    price: 150.00,
    originalPrice: 199.99,
    discount: "25%",
    featured: true,
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80",
    vendorName: "SoundMaster",
    vendorRating: 4.8,
    shippingTime: "24 horas hábiles",
    description: "Aíslate del mundo y concéntrate con la cancelación activa de ruido híbrida. Graves profundos y agudos cristalinos gracias a sus drivers de 40mm. Ligeros y con almohadillas de espuma viscoelástica.",
    specs: ["Cancelación de ruido activa", "Batería de 30 horas", "Carga rápida USB-C", "Bluetooth 5.2", "Peso: 250g"]
  },
  {
    id: 6,
    name: "Lámpara de Escritorio Inteligente LED",
    category: "Accesorios",
    price: 45.50,
    originalPrice: 45.50,
    discount: null,
    featured: false,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80",
    vendorName: "SmartHome Tech",
    vendorRating: 4.5,
    shippingTime: "2-3 días hábiles",
    description: "Ilumina tu zona de trabajo con temperatura de color ajustable. Compatible con Alexa y Google Assistant, puedes encenderla, apagarla o regular el brillo con solo usar tu voz.",
    specs: ["Control por voz / App", "Luz cálida y fría", "Sin parpadeos", "Diseño minimalista", "Brazo flexible"]
  },
  {
    id: 7,
    name: "Ratón Inalámbrico Ultra Ligero",
    category: "Accesorios",
    price: 59.90,
    originalPrice: 79.90,
    discount: "25%",
    featured: true,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80",
    vendorName: "KeyTech Store",
    vendorRating: 4.7,
    shippingTime: "24-48 horas hábiles",
    description: "Velocidad y precisión en la palma de tu mano. Con solo 65 gramos de peso y un sensor óptico de 20K DPI, este ratón se desliza perfectamente en cualquier superficie, optimizando tu flujo de trabajo.",
    specs: ["Peso: 65 gramos", "Sensor óptico 20,000 DPI", "Conexión 2.4Ghz sin lag", "Pies de PTFE 100%", "Batería de larga duración"]
  },
  {
    id: 8,
    name: "Soporte Articulado Doble para Monitor",
    category: "Accesorios",
    price: 39.99,
    originalPrice: 39.99,
    discount: null,
    featured: false,
    image: "/products/soporte_monitor.png",
    vendorName: "ErgoOffice Tech",
    vendorRating: 4.4,
    shippingTime: "3-5 días hábiles",
    description: "Ahorra espacio en tu escritorio suspendiendo tus dos pantallas en el aire. Brazos articulados con pistón de gas para ajustes suaves, permitiendo girar, inclinar y rotar tus monitores libremente.",
    specs: ["Soporte VESA 75/100", "Para monitores hasta 32\"", "Pistón de gas premium", "Gestión de cables oculta", "Construcción en aluminio"]
  },
  {
    id: 9,
    name: "Webcam 4K con Autoenfoque",
    category: "Tecnología",
    price: 110.00,
    originalPrice: 130.00,
    discount: "15%",
    featured: true,
    image: "/products/webcam_4k.png",
    vendorName: "VisionTech",
    vendorRating: 4.9,
    shippingTime: "24 horas hábiles",
    description: "Luce siempre profesional en tus reuniones virtuales. Lente de cristal gran angular, corrección automática de baja iluminación y micrófonos estéreo duales para capturar tu voz con claridad cristalina.",
    specs: ["Resolución 4K a 30fps", "Micrófonos duales con reducción de ruido", "Autoenfoque rápido", "Tapa de privacidad", "Conexión USB-C plug and play"]
  },
  {
    id: 10,
    name: "Reposamuñecas Ergonómico de Gel",
    category: "Accesorios",
    price: 18.50,
    originalPrice: 18.50,
    discount: null,
    featured: false,
    image: "/products/reposamunecas.png",
    vendorName: "StandDesk Solutions",
    vendorRating: 4.6,
    shippingTime: "2-3 días hábiles",
    description: "Cojín reposamuñecas premium con espuma viscoelástica de enfriamiento. Alivia la presión en las muñecas previniendo la fatiga durante largas sesiones de tipeo. Su base de goma antideslizante lo mantiene siempre en su lugar.",
    specs: ["Interior de espuma viscoelástica", "Superficie de tela transpirable", "Base antideslizante", "Diseño curvo anatómico", "Tamaño para teclado completo"]
  },
  {
    id: 11,
    name: "Hub USB-C Multipuertos 7 en 1",
    category: "Accesorios",
    price: 35.00,
    originalPrice: 45.00,
    discount: "22%",
    featured: true,
    image: "/products/hub_usbc.png",
    vendorName: "KeyTech Store",
    vendorRating: 4.8,
    shippingTime: "24 horas hábiles",
    description: "Expande la conectividad de tu laptop. Incluye HDMI 4K, 3 puertos USB 3.0, lectores de tarjetas SD/TF y un puerto de carga USB-C PD 100W.",
    specs: ["HDMI 4K@30Hz", "USB-C PD 100W", "Carcasa de aluminio disipador", "Plug and Play", "Compatible con Mac y Windows"]
  },
  {
    id: 12,
    name: "Soporte Elevador de Aluminio para Laptop",
    category: "Mobiliario",
    price: 29.99,
    originalPrice: 35.00,
    discount: "14%",
    featured: false,
    image: "/products/laptop_stand.png",
    vendorName: "StandDesk Solutions",
    vendorRating: 4.5,
    shippingTime: "2-3 días hábiles",
    description: "Eleva la pantalla de tu portátil al nivel de tus ojos para mejorar la postura. Fabricado en aleación de aluminio premium que también ayuda a disipar el calor.",
    specs: ["Plegable y portátil", "Aluminio premium", "Soporta laptops de 10\" a 15.6\"", "Almohadillas de silicona protectoras", "Ventilación abierta"]
  },
  {
    id: 13,
    name: "Micrófono de Condensador USB",
    category: "Tecnología",
    price: 65.00,
    originalPrice: 80.00,
    discount: "18%",
    featured: true,
    image: "/products/usb_mic.png",
    vendorName: "SoundMaster",
    vendorRating: 4.7,
    shippingTime: "24-48 horas hábiles",
    description: "Captura tu voz con calidad de estudio. Perfecto para podcasting, streaming o videoconferencias. Patrón cardioide para minimizar el ruido de fondo.",
    specs: ["Patrón polar cardioide", "Frecuencia 20Hz-20kHz", "Filtro pop incluido", "Control de ganancia físico", "Soporte de escritorio"]
  },
  {
    id: 14,
    name: "Lámpara de Monitor LED (Screenbar)",
    category: "Accesorios",
    price: 49.50,
    originalPrice: 49.50,
    discount: null,
    featured: false,
    image: "/products/screenbar.png",
    vendorName: "SmartHome Tech",
    vendorRating: 4.9,
    shippingTime: "3-5 días hábiles",
    description: "Ilumina tu escritorio sin reflejos en la pantalla. Esta lámpara se coloca sobre tu monitor y dirige la luz hacia abajo, cuidando tu vista en sesiones nocturnas.",
    specs: ["Diseño asimétrico óptico", "Brillo auto-ajustable", "3 temperaturas de color", "Ahorro de espacio", "Conexión USB"]
  },
  {
    id: 15,
    name: "Mousepad Gamer XXL RGB",
    category: "Accesorios",
    price: 24.99,
    originalPrice: 30.00,
    discount: "16%",
    featured: false,
    image: "/products/mousepad_rgb.png",
    vendorName: "KeyTech Store",
    vendorRating: 4.6,
    shippingTime: "24-48 horas hábiles",
    description: "Superficie microtexturizada optimizada para todos los sensores. Borde con iluminación RGB de 14 modos y tamaño extendido para cubrir teclado y ratón.",
    specs: ["Tamaño: 800x300mm", "Superficie impermeable", "14 modos RGB", "Base de goma antideslizante", "Memoria de modo de luz"]
  },
  {
    id: 16,
    name: "Estación de Carga Inalámbrica 3 en 1",
    category: "Tecnología",
    price: 42.00,
    originalPrice: 50.00,
    discount: "16%",
    featured: true,
    image: "/products/wireless_charger.png",
    vendorName: "DigitalDisplays Pro",
    vendorRating: 4.8,
    shippingTime: "24 horas hábiles",
    description: "Carga tu smartphone, auriculares y smartwatch simultáneamente. Diseño plegable ideal para el escritorio o la mesa de noche. Carga rápida Qi de 15W.",
    specs: ["Carga rápida 15W", "Para iPhone/Android", "Diseño plegable", "Protección contra sobrecarga", "Indicador LED inteligente"]
  },
  {
    id: 17,
    name: "Archivador Metálico de 3 Cajones",
    category: "Mobiliario",
    price: 129.99,
    originalPrice: 149.99,
    discount: "13%",
    featured: false,
    image: "/products/metal_cabinet.png",
    vendorName: "ErgoOffice Tech",
    vendorRating: 4.4,
    shippingTime: "5-7 días hábiles",
    description: "Mantén tus documentos seguros y organizados. Construcción en acero laminado en frío, con cerradura central que asegura los 3 cajones y ruedas bloqueables.",
    specs: ["Acero laminado en frío", "Cerradura central con 2 llaves", "5 ruedas anti-vuelco", "Para carpetas tamaño carta/A4", "Capacidad: 150kg"]
  },
  {
    id: 18,
    name: "Webcam Cover (Pack de 6)",
    category: "Accesorios",
    price: 8.99,
    originalPrice: 8.99,
    discount: null,
    featured: false,
    image: "/products/webcam_cover.png",
    vendorName: "VisionTech",
    vendorRating: 4.2,
    shippingTime: "1-2 días hábiles",
    description: "Protege tu privacidad de posibles hackeos. Diseños ultra delgados que no impiden cerrar la laptop. Fáciles de instalar y de deslizar para abrir o cerrar.",
    specs: ["Grosor ultra delgado 0.027\"", "Adhesivo 3M resistente", "Pack de 6 piezas", "Diseño deslizante", "Compatible con laptops/tablets"]
  },
  {
    id: 19,
    name: "Router Wi-Fi 6 Mesh System",
    category: "Tecnología",
    price: 249.99,
    originalPrice: 299.99,
    discount: "16%",
    featured: true,
    image: "/products/wifi_router.png",
    vendorName: "SmartHome Tech",
    vendorRating: 4.9,
    shippingTime: "2-3 días hábiles",
    description: "Elimina las zonas sin internet en tu oficina u hogar. Cobertura de hasta 500 metros cuadrados con velocidad Gigabit Wi-Fi 6. Soporta hasta 150 dispositivos conectados.",
    specs: ["Wi-Fi 6 AX3000", "Cobertura de 500m2", "Conexión estable", "Control parental inteligente", "Setup fácil por app"]
  },
  {
    id: 20,
    name: "Pizarra Magnética de Cristal",
    category: "Mobiliario",
    price: 89.00,
    originalPrice: 89.00,
    discount: null,
    featured: false,
    image: "/products/glass_board.png",
    vendorName: "StandDesk Solutions",
    vendorRating: 4.5,
    shippingTime: "3-5 días hábiles",
    description: "Dale un toque moderno a tu oficina para brainstormings. Cristal templado negro antimanchas, magnética y sin bordes. Incluye 4 imanes de neodimio fuertes.",
    specs: ["Cristal templado resistente", "Superficie antimanchas", "Magnética", "Montaje invisible", "Tamaño 90x60cm"]
  },
  {
    id: 21,
    name: "Cable Organizador Neopreno (Manga)",
    category: "Accesorios",
    price: 15.50,
    originalPrice: 15.50,
    discount: null,
    featured: false,
    image: "/products/cable_sleeve.png",
    vendorName: "ErgoOffice Tech",
    vendorRating: 4.7,
    shippingTime: "24-48 horas hábiles",
    description: "Oculta el desorden de cables de tu escritorio. Manga de neopreno flexible con cierre de velcro que permite sacar cables por cualquier lado.",
    specs: ["Largo: 3 metros (cortable)", "Material de neopreno premium", "Reversible negro/blanco", "Cierre fácil de velcro", "Alta capacidad"]
  }
];
